-- =============================================================================
-- V1 — Baseline platform schema (tenancy, identity, RBAC, audit).
-- Portable across H2 (PostgreSQL compatibility mode) and PostgreSQL.
-- Owned by Flyway; Hibernate runs in validate mode and never alters schema.
-- Clinical/domain tables are introduced in later migrations alongside M3 entities.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Multi-tenancy: every tenant-scoped table carries tenant_id (enforced in app
-- and verified by tests). A tenant is a hospital network / customer.
-- ---------------------------------------------------------------------------
CREATE TABLE tenant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tenant_code UNIQUE (code)
);

-- ---------------------------------------------------------------------------
-- Organizations (hospitals) and their branches/departments.
-- ---------------------------------------------------------------------------
CREATE TABLE hospital (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    timezone        VARCHAR(64)  NOT NULL DEFAULT 'UTC',
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hospital_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT uq_hospital_code UNIQUE (tenant_id, code)
);

CREATE TABLE department (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    hospital_id     BIGINT       NOT NULL,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_department_hospital FOREIGN KEY (hospital_id) REFERENCES hospital (id),
    CONSTRAINT uq_department_code UNIQUE (hospital_id, code)
);

-- ---------------------------------------------------------------------------
-- Identity & RBAC: users, roles, permissions, and their join tables.
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL,
    username            VARCHAR(100) NOT NULL,
    email               VARCHAR(200) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    full_name           VARCHAR(200) NOT NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    email_verified      BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_login_count  INTEGER      NOT NULL DEFAULT 0,
    locked_until        TIMESTAMP,
    last_login_at       TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT uq_user_username UNIQUE (tenant_id, username),
    CONSTRAINT uq_user_email UNIQUE (tenant_id, email)
);

CREATE TABLE role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    CONSTRAINT uq_role_code UNIQUE (code)
);

CREATE TABLE permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    CONSTRAINT uq_permission_code UNIQUE (code)
);

CREATE TABLE user_role (
    user_id         BIGINT NOT NULL,
    role_id         BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE role_permission (
    role_id         BIGINT NOT NULL,
    permission_id   BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_perm_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_role_perm_perm FOREIGN KEY (permission_id) REFERENCES permission (id)
);

-- ---------------------------------------------------------------------------
-- Audit log: every important action is recorded with before/after context.
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT,
    occurred_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor           VARCHAR(200),
    action          VARCHAR(100) NOT NULL,
    entity_type     VARCHAR(100),
    entity_id       VARCHAR(100),
    ip_address      VARCHAR(64),
    correlation_id  VARCHAR(64),
    request_id      VARCHAR(64),
    old_value       CLOB,
    new_value       CLOB
);

-- ---------------------------------------------------------------------------
-- Indexes for common access paths.
-- ---------------------------------------------------------------------------
CREATE INDEX idx_hospital_tenant      ON hospital (tenant_id);
CREATE INDEX idx_department_tenant    ON department (tenant_id);
CREATE INDEX idx_user_tenant          ON app_user (tenant_id);
CREATE INDEX idx_audit_tenant_time    ON audit_log (tenant_id, occurred_at);
CREATE INDEX idx_audit_entity         ON audit_log (entity_type, entity_id);
