-- =============================================================================
-- V2 — Clinical core schema (patient, provider, appointment).
-- Tenant-scoped, with foreign keys, unique business keys, and indexes.
-- Portable across H2 (PostgreSQL mode) and PostgreSQL. Extends the V1 baseline.
-- =============================================================================

CREATE TABLE patient (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    mrn             VARCHAR(40)  NOT NULL,            -- medical record number
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    date_of_birth   DATE         NOT NULL,
    gender          VARCHAR(20)  NOT NULL DEFAULT 'UNKNOWN',
    email           VARCHAR(200),
    phone           VARCHAR(40),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_patient_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT uq_patient_mrn UNIQUE (tenant_id, mrn)
);

CREATE TABLE provider (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    hospital_id     BIGINT,
    code            VARCHAR(40)  NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    specialty       VARCHAR(100),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_provider_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_provider_hospital FOREIGN KEY (hospital_id) REFERENCES hospital (id),
    CONSTRAINT uq_provider_code UNIQUE (tenant_id, code)
);

CREATE TABLE appointment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL,
    patient_id       BIGINT      NOT NULL,
    provider_id      BIGINT      NOT NULL,
    scheduled_start  TIMESTAMP   NOT NULL,
    scheduled_end    TIMESTAMP   NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'BOOKED',
    reason           VARCHAR(500),
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appt_tenant   FOREIGN KEY (tenant_id)   REFERENCES tenant (id),
    CONSTRAINT fk_appt_patient  FOREIGN KEY (patient_id)  REFERENCES patient (id),
    CONSTRAINT fk_appt_provider FOREIGN KEY (provider_id) REFERENCES provider (id)
);

CREATE INDEX idx_patient_tenant       ON patient (tenant_id);
CREATE INDEX idx_patient_last_name    ON patient (tenant_id, last_name);
CREATE INDEX idx_provider_tenant      ON provider (tenant_id);
CREATE INDEX idx_appt_tenant          ON appointment (tenant_id);
CREATE INDEX idx_appt_provider_time   ON appointment (provider_id, scheduled_start);
CREATE INDEX idx_appt_patient         ON appointment (patient_id);
